name: Tools - PR Validation

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/tools/**' # Only trigger on changes to tools package

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: packages/tools
        run: npm install --also=dev

      - name: Build tools package
        working-directory: packages/tools
        run: npm run build

      - name: Run tools tests
        working-directory: packages/tools
        run: npm run test
